# Uncomment the next line to define a global platform for your project
#platform :ios, '10.0'

target 'DropIt' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DropIt



pod 'Firebase/Firestore'
  
   pod 'Firebase/Crashlytics'


   pod 'Firebase/Analytics'
   
   pod 'Firebase/Auth'

   pod 'Firebase/Storage'
   
   pod 'Firebase/Messaging'
   
   pod 'Firebase/Core'
   
   pod 'FirebaseFirestoreSwift'
   
   pod 'GoogleSignIn'

 pod 'TTGSnackbar'
 
 pod 'IQKeyboardManagerSwift'

 pod 'Stripe', '~> 22.8'
 
 
 

 
 pod 'SDWebImage', '~> 4.0'

pod 'CropViewController'

pod 'FSCalendar'


 pod 'AMPopTip', '4.4.0'


 pod 'LayoutHelper', '1.0.0'
 
 pod 'lottie-ios', '3.2.1'

 pod 'MBProgressHUD', '1.2.0'
 
 pod 'Moya', '14.0.0'

 pod 'Moya-ObjectMapper', '2.9'

 pod 'ObjectMapper', '4.2.0'
 
 pod 'ReachabilitySwift', '5.0.0'
  
 pod 'SwiftLint', '0.43.1'

 pod 'XCDYouTubeKit', '2.15.2'

 pod 'youtube-ios-player-helper', '1.0.2'

 pod 'Kingfisher'


end
