//
//  ConditionsViewController.swift
//  DropIt
//
//

import UIKit

class ConditionsViewController: UIViewController {
    
    @IBOutlet private weak var termsTextView: UITextView!
    
    // MARK: - Lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupTextView()
    }
    
    // MARK: - Setup
    private func setupTextView() {
        termsTextView.text = "This TERMS OF USE Agreement (Agreement) is made by “DVIRALlink”\n\nThis Agreement contains the complete terms and conditions that govern the use of the DVIRALlink app(s). BY CLICKING THE “I AGREE” BUTTON BELOW OR BY ACCESSING, VISITING, BROWSING, USING OR ATTEMPTING TO INTERACT WITH OR USE ANY PART OF THIS APP, SERVICES, WEBSITES OR CONTENT (COLLECTIVELY “SERVICES”), YOU AGREE THAT YOU HAVE READ, UNDERSTAND AND AGREE TO BE BOUND BY THIS AGREEMENT.\n\n"
        termsTextView.text += "IF YOU DO NOT AGREE TO BE BOUND BY THIS AGREEMENT, DO NOT ACCESS OR USE ANY PART OF THIS APP. DVIRALlink RESERVES THE RIGHT, WITH OR WITHOUT NOTICE, TO MAKE CHANGES TO THIS AGREEMENT AT DVIRALlink’S DISCRETION. CONTINUED USE OF ANY PART OF THIS APP CONSTITUTES YOUR ACCEPTANCE OF SUCH CHANGES.\n\n"
        termsTextView.text += "1. Purpose: This app is hosting service. Registered users of the app may upload and post audio,text, photos, pictures, graphics, comments, and other content, data or information, which will be posted by DVIRALlink at the direction of such registered users, and may be shared and distributed by such registered users, and other users of the APP. The app allows parties to communicate with one another regarding the information posted on DVIRALlink.\n\n"
        termsTextView.text += "2. Access to this site. To access this app, app resources, links or other content, you may be asked to provide certain registration details or other information. It is a condition of your use of this site that all the information you provide will be correct, current, and complete. If DVIRALlink believes the information you provide is not correct, current, or complete, DVIRALlink has the right to deny access to this site, or to any of its resources, and to terminate or suspend your access at any time."
        termsTextView.text += "3. Applicable use of this app. You may use this app for purposes expressly permitted by this app. As a condition of your use of DVIRALlink’s APP, you warrant to DVIRALlink that you will not use the app for any purpose that is unlawful or prohibited by these terms, conditions, and notices.\n\n"
        termsTextView.text += "4. We allow selected artists (“Artists”) in a variety of fields to post their art, music, and/or representations of their music and/or art on this app (the “APP”). We permit Users who agree to these Terms of Use to view such Artist Materials on this app. Users may also contact the Artists directly to purchase music, art, and/or music related services. Any communications or transactions between the users and Artists are handled between the Users and the Artist and we are not involved and take no responsibility whatsoever in connection with those activities.\n\n"
        termsTextView.text += "5. These Terms of Service and corresponding Privacy Policy apply to all Services and extend to all of our users. Our Services may contain links to third party websites and services that are not owned or controlled by DVIRALlink and we cannot control, and will not be held responsible for, the content, privacy policies, or practices of any third party websites or services. By using the DVIRALlink and Services, you specifically release DVIRALlink from any and all liability arising from your use of any third party website, third party services, or interaction with any third party.\n\n"
        termsTextView.text += "6. No Unlawful Access: You agree that you will not use DVIRALlink app in any manner that could in any way disable, overburden, damage, or impair the APP or otherwise interfere with any other party’s use and enjoyment of the APP. You further agree that you will not obtain, or attempt to obtain, any materials, content, or information by any means not expressly made available or provided for through authorized use of the APP.\n\n"
        termsTextView.text += "7. Code of Conduct: DVIRALlink gives users a virtual platform where they can interact and communicate with one another about music and/or art. “User Posts” refer to all information, data, text, software, music, sound, photographs, graphics, video, messages, tags, or other materials—whether publicly posted or privately transmitted on the DVIRALlink."
        termsTextView.text += "If you choose to post User Posts on the DVIRALlink app, we require that you adhere to generally accepted rules of etiquette and standards of behavior. Your use of our Services reflects your respect for the legal rights of users connected with DVIRALlink. By using the Services and submitting User Posts, you understand that the User Posts are subject to the DVIRALlink Privacy Policy.\n\n"
        termsTextView.text += "8. By using DVIRALlink and participating in the DVIRALlink Services, you agree that your User Posts will not contain anything that is or could appear to be:\n\n"
        termsTextView.text += "• Threatening, bullying, harmful, stalking another user, harassing, hateful;\n• Racially, ethnically, or otherwise objectionable;\n• Offensive language;\n• Untrue, misleading, libelous, invasive to another person’s privacy or protected data;\n• Pornographic, sexually explicit, unlawful or plagiarized;\n• Infringing or allegedly infringing on a third party’s intellectual property rights, including patent, trade secret, copyright, trademark, right of publicity or other proprietary rights;\n• Anything that you do not have the legal right to transfer;\n"
        termsTextView.text += "• Anything that you are legally bound not to disclose under contractual or fiduciary relationships including, but not limited to, inside information or proprietary and confidential business information;\n• Unsolicited, undisclosed, or unauthorized advertising;\n"
        termsTextView.text += "• Software viruses or any other malicious computer code, files, or programs designed to interrupt, destroy, or limit the functionality of any computer software, hardware, or telecommunication equipment;\n• Data or information obtained by the unauthorized access of another’s computer or account with which such a posting or submission would constitute unauthorized use; and\n• Any other post or submission that violates applicable local, state, national orinternational law, regulation or statute (including export laws).\n\n"
        termsTextView.text += "9. DVIRALlink takes conduct and use violations very seriously. If you use the Services in a prohibited way listed above, or if you use the Services in a way that DVIRALlink deems to be unacceptable, it will result in immediate account suspension or cancellation and the possibility that DVIRALlink will pursue civil remedies without providing advance notice.\n\n"
        termsTextView.text += "10. User Data: DVIRALlink does not own any data, information, or material that you submit to the Services (“User Data”). You, not DVIRALlink, are fully responsible for the quality, integrity, legality, accuracy, intellectual property ownership, reliability, appropriateness, or the right to use all of the User Data. ABC cannot be held responsible for the deletion, correction, destruction, damage, loss or failure to store any User Data.\n\n"
        termsTextView.text += "11. User Accounts: When you sign up for a User Account with DVIRALlink, you are required to give us true, accurate, current and complete information about yourself in all required fields of our registration form. If your information changes, it is your responsibility to update your account to reflect these changes. If ABC feels that your account information is not complete, current, or accurate, or that your account violates these Terms of Service, ABC may suspend or terminate your account.\n\n"
        termsTextView.text += "12. Responsibility for User Posts: Any User Posts that are either posted publicly or privately on the DVIRALlink APP is the sole responsibility of the user who posted it. Your access to the DVIRALlink and User Posts is AT YOUR OWN RISK. DVIRALlink cannot be held responsible for any damage resulting from errors or omission in User Posts or User Data or any damage that is suffered as a result.\n\n"
        termsTextView.text += "13. User Post Content Disclaimer: DVIRALlink may contain User Posts or links to content that direct you to websites you find inappropriate or offensive. DVIRALlink has no way to control nor does it have a duty to take any action with regard to how you interpret or use content on DVIRALlink app. You are solely responsible for how you view and interpret User Posts on the DVIRALlink.\n\n"
        termsTextView.text += "14. User Identity Disclaimer: DVIRALlink cannot guarantee the identity of any users with whom you interact on our Services. DVIRALlink also cannot guarantee which users gain access to the Services. Your use of the DVIRALlink app is AS IS and AT YOUR OWN RISK.\n\n"
        termsTextView.text += "15. Monitoring User Post: DVIRALlink expressly disclaims any and all liability in connection with User Posts. BY USING OUR SERVICES YOU UNDERSTAND AND AGREE THAT DVIRALlink RESERVES THE RIGHT, BUT DOES NOT ASSUME RESPONSIBILITY, TO MONITOR USER POSTS ON OUR SERVICES. ALL CONTENT ON THIS APP IS PRESENTED TO YOU “AS IS” AND “AT YOUR OWN RISK.”\n\n"
        termsTextView.text += "16. Term and Termination: By using our APP, you understand and agree that DVIRALlink, at its sole discretion, and with or without cause or notice to you, can terminate these Terms of Use, your access to the APP, or suspend or block your access to the APP. In the event that termination occurs, DVIRALlink retains the ability to exploit the electronic or printed materials it has created, or developed specific plans to create, that contain such User Posts."
        termsTextView.text += " DVIRALlink reserves the right to modify or remove User Posts in its sole discretion and without prior notice. DVIRALlink also reserves the right to terminate a user’s account and access to Services at any time in its sole discretion and without prior notices. If DVIRALlink suspends or cancels your account, your right to use the Services will stop immediately. Once your account is cancelled and deleted, you will not have access to any User Data that you contributed on our Services.\n\n"
        termsTextView.text += "17. Representation of Warranties: You represent and you warrant that you are legally able to form a binding contract with DVIRALlink, and you are not barred from receiving Services under the laws of the United States or other jurisdictions. You agree to provide current and accurate identification, contact, and other information as part of the registration process for access to our Services."
        termsTextView.text += "You agree to be solely responsible for all content on your account. Your account, including your username and password, are personal to you and should not be used by any other user or legal entity. You agree to be solely responsible for maintaining the confidentiality of your account information, and you are responsible for all activities that occur under your account. You agree to immediately notify DVIRALlink of any unauthorized use of your account or any other breach of security."
        termsTextView.text += "DVIRALlink will not be liable for any loss or damage arising from your failure to provide us with accurate information or to keep your account secure. You understand that all User Posts and User Data are the sole responsibility of the account owner from which the User Post or User Data originated. DVIRALlink does not claim ownership to or responsibility for, any User Post or User Data. DVIRALlink reserves the right, but does not assume the responsibility, to monitor or review any activity on DVIRALlink’s Services. "
        termsTextView.text += "You agree that you are responsible for the conduct of your account and any User Data that is created, transmitted, stored, or displayed by, from, or within your account while using the Services. You will be held responsible for any consequences, legal or otherwise, that arise from your use of the Services. You agree to use our Services only for purposes that are legal, proper and according to the Terms of Service, corresponding Privacy Policy, and any applicable policies or guidelines. "
        termsTextView.text += "You agree that you will not engage in any activity that interferes with or disrupts DVIRALlink services or servers or networks connected to DVIRALlink services. You represent and you warrant that you will not use DVIRALlink Services in any way considered “prohibited”. These actions are subject to the strict regulation of DVIRALlink and are grounds for suspension or termination of your account. "
        termsTextView.text += "You represent and warrant to DVIRALlink that Your content is an original work by you, or you have obtained all rights, licenses, consents, and permission necessary in order to use at any and all times during any applicable use, and to authorize DVIRALlink to use."
        termsTextView.text += " You represent your content on DVIRALlink does not and will not infringe or violate the rights of any third party, including without limitation, any intellectual property rights, performers’ rights, rights of privacy or publicity, or rights in confidential information. You have obtained all necessary consents, permissions and/or releases. "
        termsTextView.text += "Your Content does not and will not create any liability on the part of DVIRALlink, its subsidiaries, affiliates, successors, and assigns, and their respective employees, agents, directors, officers and/or shareholders.\n\n"
        termsTextView.text += "18. By registering for and using our Services: You agree to provide current and accurate identification, contact, and other information as part of the registration process for access to our Services. You agree to be solely responsible for all content on your account. Your account, including your username and password, are personal to you and should not be used by any other user or legal entity. "
        termsTextView.text += "You agree to be solely responsible for maintaining the confidentiality of your account information, and you are responsible for all activities that occur under your account. You agree to immediately notify DVIRALlink of any unauthorized use of your account or any other breach of security. DVIRALlink will not be liable for any loss or damage arising from your failure to provide us with accurate information or to keep your account secure. "
        termsTextView.text += "DVIRALlink does not claim ownership to or responsibility for, any User Post or User Data. DVIRALlink reserves the right, but does not assume the responsibility, to monitor or review any activity on DVIRALlink’s Services. You agree that you are responsible for the conduct of your account and any User Data that is created, transmitted, stored, or displayed by, from, or within your account while using the Services. "
        termsTextView.text += "You will be held responsible for any consequences, legal or otherwise, that arise from your use of the Services. You agree to use our App only for purposes that are legal, proper and according to the Terms of Service, corresponding Privacy Policy, and any applicable policies or guidelines. You agree that you will not engage in any activity that interferes with or disrupts DVIRALlink app or servers or networks connected to DVIRALlink app."
        termsTextView.text += "You represent and you warrant that you will not use DVIRALlink app in any way considered “prohibited” (please read the “Use of Services” section above for more information). These actions are subject to the strict regulation of DVIRALlink and are grounds for suspension or termination of your account.\n\n"
        termsTextView.text += "19. Indemnification: By accessing, registering for, using, or downloading our Services you agree to indemnify, defend and hold harmless DVIRALlink, its officers, employees, agents, directors, subsidiaries, affiliates, successors, assigns, suppliers, or licensors from any liability, loss, claim and expense (including attorneys’ reasonable fees) related to:"
        termsTextView.text += " Any claim due to or arising out of your violation of the Terms of Service, including but not limited to a claim arising out of a breach of your representations or warranties made under these Terms of Service; Your use of and/or access (or any use or access by a third party on your account) to the app or Services; Your violation of any third party right, including without limitation, any copyright, property, moral or privacy right; or The unavailability of app or Services.\n\n"
        termsTextView.text += "20. Copyright Infringement: If you believe that your work has been copied in a way that constitutes copyright infringement, you must provide DVIRALlink’s Copyright Agent with the following information:\n\n"
        termsTextView.text += "An electronic or physical signature of the person authorized to act on behalf of the copyright owner or other intellectual property interest;\n\n"
        termsTextView.text += "A description of the copyrighted work or other intellectual property that you claim has been infringed;\n\n"
        termsTextView.text += "A description of where the allegedly infringing material is located on the ABC Services, with enough detail that we are able to find it on the Services;\n\n"
        termsTextView.text += "Your Address, Telephone Number, and Email Address where you may be reached;\n\n"
        termsTextView.text += "A statement by you that you have a good faith belief that the use of the material is not authorized by copyright or intellectual property owner, it’s agent, or the law;\n\n"
        termsTextView.text += "A statement made by you, under the penalty of perjury, that the information in your notice is accurate and that you are the copyright or intellectual property owner or that you are authorized to act on their behalf;\n\n"
        termsTextView.text += "Our Designated Copyright Agent to receive notifications of claimed infringement is;\n\n"
        termsTextView.text += "\t\t\tCOPYRIGHT AGENT\n\t\t\tPlease Indicate Address here:\n\t\t\tProvide email here\n\n"
        termsTextView.text += "21. Security: Any passwords used for this site are for individual use only. You will be responsible for the security of your password(s). From time to time, DVIRALlink may require that you change your password. You are prohibited from using any services or facilities provided in connection with this site to compromise security or tamper with system resources and/or accounts."
        termsTextView.text += "The use or distribution of tools designed for compromising security (e.g., password crackers, rootkits, Trojan horses, or network probing tools) is strictly prohibited. If you become involved in any violation of system security, DVIRALlink reserves the right to release your account details to system administrators at other websites and/or the authorities in order to assist them in resolving security incidents."
        termsTextView.text += "DVIRALlink reserves the right to investigate suspected violations of these Terms of Use. DVIRALlink reserves the right to fully cooperate with any law enforcement authorities or court order requesting or direction DVIRALlink to disclose the identity of anyone posting any e-mail messages, or publishing or otherwise making available any materials that are believed to violate these Terms of Use.\n\n"
        termsTextView.text += "22. BY ACCEPTING THIS AGREEMENT YOU WAIVE ALL RIGHTS AND AGREE TO HOLD DVIRALlink HARMLESS FROM ANY CLAIMS RESULTING FROM ANY ACTION TAKEN BY DVIRALlink DURING OR AS A RESULT OF ITS INVESTIGATIONS AND/OR FROM ANY ACTIONSTAKEN AS A CONSEQUENCE OF INVESTIGATIONS BY EITHER DVIRALlink OR LAWENFORCEMENT AUTHORITIES.\n\n"
        termsTextView.text += "23. Miscellaneous: These terms of use will be governed and interpreted pursuant to the laws of New York, notwithstanding any principles of conflicts of law. You specifically consent to personal jurisdiction in New York in connection with any dispute between you and DVIRALlink arising out of these Terms of Use or pertaining to the subject matter hereof. The parties to these Terms of Use each agree that the exclusive venue for any dispute between the parties arising out of these Terms of Use will be in the state and federal courts in Queens, New York.\n\n"
        termsTextView.text += "24. If any part of these Terms of use is unlawful, void or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of any remaining provisions. You agree that no joint venture, partnership, employment, or agency relationship exists between you and DVIRALlink as a result of this agreement or use of DVIRALlink’s app."
        termsTextView.text += "These Terms of use constitute the entire agreement among the parties relating to this subject matter and supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written between the user and DVIRALlink with respect to DVIRALlink’s app. Notwithstanding the foregoing, any additional terms and conditions on this site will govern the items to which they pertain. DVIRALlink may revise these Terms of Use at any time by updating this posting.\n\n"
        termsTextView.text += "In the event that a claim, suit, or action (“Suit”) is brought against you, we will provide notice of this Suit to your contact information we have on file.\n\n"
        termsTextView.text += "If you are in agreement with these Terms of Use, please click “I Agree” below. If you do not agree with these Terms of Use, click on the button below that says, “No, thank you,” in which case will you be not be permitted to access the app.\n\n"
    }
    
    // MARK: - Actions
    @IBAction private func tappedBackButton(_ sender: UIBarButtonItem) {
        dismiss(animated: true, completion: nil)
    }
    
}
